architecture: replication

auth:
  enabled: true
  # NOTE: 실제 운영에서는 existingSecret 사용을 권고합니다.
  password: "REPLACE_ME"

master:
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 50Gi
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      cpu: "2"
      memory: 8Gi

replica:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 50Gi
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      cpu: "2"
      memory: 8Gi

sentinel:
  enabled: true
  # 3 sentinels 권고
  replicas: 3

